# Generated by Django 3.0.3 on 2020-07-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200715_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click on the above link to read the blog post', max_length=255),
        ),
    ]
